name: Deploy Application to Live Server

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  live-server-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd public_html
            git fetch --all
            git reset --hard origin/main
